const C_MSG =  {
    technical_err: "Oops! Something Went Worng.",
    forgot_pwd_document_title : `Forgot Password | ${process.env.REACT_APP_SITE_NAME} - User Forgot Password`,
    lockscreen_document_title : `Login Again | ${process.env.REACT_APP_SITE_NAME} - User Account locked`,
    login_document_title : `Login | ${process.env.REACT_APP_SITE_NAME} - User Login`,
    login_otp_document_title : `Verify OTP | ${process.env.REACT_APP_SITE_NAME} - Verify User OTP`,
    register_document_title : `SignUp | ${process.env.REACT_APP_SITE_NAME} - User Signup`,
    reset_pwd_document_title : `Reset Password | ${process.env.REACT_APP_SITE_NAME} - User Reset Password`,
    user_settings_document_title : `User Settings | ${process.env.REACT_APP_SITE_NAME} - User Settings Page`,
    admin_settings_document_title : `Admin Settings | ${process.env.REACT_APP_SITE_NAME} - Admin Settings Page`,
    admin_users_settings_document_title : `Admin Settings | ${process.env.REACT_APP_SITE_NAME} - Users Setting Page`,
    admin_requests_settings_document_title : `User Requests | ${process.env.REACT_APP_SITE_NAME} - User Requests Page`,
    user_expense_personal_page_title : `Personal Expenses | ${process.env.REACT_APP_SITE_NAME} - Users Personal Expenses`,
    user_expense_approver_page_title : `Approver Expenses | ${process.env.REACT_APP_SITE_NAME} - Users Approver Expenses`,
    user_expense_finance_page_title : `Finance Expenses | ${process.env.REACT_APP_SITE_NAME} - Users Finance Expenses`,
    user_txns_personal_page_title : `Personal Transactions | ${process.env.REACT_APP_SITE_NAME} - Users Personal Transactions`,
    user_txns_approver_page_title : `Approver Transactions | ${process.env.REACT_APP_SITE_NAME} - Users Approver Transactions`,
    user_txns_finance_page_title : `Finance Transactions | ${process.env.REACT_APP_SITE_NAME} - Users Finance Transactions`,
    user_invoices_page_title : `Invoices | ${process.env.REACT_APP_SITE_NAME} - Users Invoices`,
    user_reports_page_title : `User Report | ${process.env.REACT_APP_SITE_NAME} - Users Report`,

    field_required: "Field is Required",
    payee_name_required: "Please select payee name",
    payee_gst_required: "Please enter gst number",
    payee_invoice_required: "Please enter invoice",
    
    uname_required: "Please enter username",
    fname_required: "Please enter first name",
    lname_required: "Please enter last name",
    email_required: "Please enter email",
    addr_required: "Please enter Address",
    ph_number_required: "Please enter phone number",
    pass_required: "Please enter password",
    conf_pass_required: "Please enter confirm password",
    password_mismatch: "Password and confirm password does not match",
    bank_name_required: "Please enter bank name",
    branch_name_required: "Please enter branch name",
    ifsc_code_required: "Please enter IFSC Code",
    account_no_required: "Please enter account number",
    upi_required: "Please enter upi id",

    group_name_required: "Group name required",
    user_select_required: "Atleast 1 user should be selected",
    category_name_required: "Category name required",
    project_name_required: "Project name required",
    project_desc_required: "Project Description required",
    acc_holder_name_required: "Account holder name required",
    acc_no_required: "Account number required",
    bank_name_required: "Bank name required",
    branch_name_required: "Branch name required",
    ifsc_code_required: "IFSC code required",
    swift_code_required: "Swift code required",
    account_type_required: "Account type required",
    upi_id_required: "UPI id required",
    role_select_required: "Atleast 1 role should be selected",
    pay_mthd_required: "Please enter payment method",
    pay_acc_required: "Please select payment account",
    ref_no_required: "Please add reference number",
    expense_details_required: "Please add expense details",
    name_required: "Please enter name",
    rej_reason_required: "Please enter reason",
    amt_required: "Please enter amount",
    tax_amt_required: "Please enter amount",
    date_required: "Please enter date",
    vendor_required: "Please Select vendor",
    category_required: "Please Select Category",
    tax_slab_required: "Please Select Tax Slab",
    desc_required: "Please Enter Description",
    file_required: "Please Select File",
    file_upload_success: "Files uploaded successfully",
    select_valid_file_format: "Please Select Valid File Format",
    supported_file_format:"Supported Format : doc, docx, pdf, xls, xlsx, png, gif, jpg, jpeg, jfif, svg, webp, msg, eml, zip",
    

}

export default C_MSG